version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: filesize
    versions:
    - 6.1.0
    - 6.2.1
    - 6.2.2
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: jsdom
    versions:
    - 16.4.0
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: jsonld
    versions:
    - 3.3.0
    - 3.3.2
    - 4.0.1
    - 5.0.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
